version: '3.9'
x-env: &env-vars
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: p0stgr3slocal
  POSTGRES_DB: sqlerpostgres
  POSTGRES_PORT: 5432
x-env-sqler: &env-tokens
  GITHUB_TOKEN: ${GITHUB_TOKEN}
  NPM_TOKEN: ${NPM_TOKEN}
services:
  # PostgreSQL: https://hub.docker.com/_/postgres
  sqler_postgres:
    image: postgres:latest
    container_name: sqler_postgres
    restart: always
    environment:
      <<: *env-vars
    networks:
      - app
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB" -p "$$POSTGRES_PORT"
      timeout: 20s
      retries: 10
    ports:
      - 5432:5432
  # NodeJS for sqler dialect testing
  sqler_postgres_dialect:
    container_name: sqler_postgres_dialect
    depends_on:
      - sqler_postgres
    build:
      context: .
      dockerfile: Dockerfile.ci
      args:
        <<: *env-vars
    links:
      - "sqler_postgres:sqler_postgres_database"
    networks:
      - app
    healthcheck:
      test: curl --fail http://localhost:80/healthcheck || exit 1
      timeout: 20s
      retries: 10
    ports:
      - 4003:80
    restart: unless-stopped
    environment:
      <<: [ *env-vars, *env-tokens ]
    volumes:
      - ./docs:/home/node/app/docs
networks:
  app:
    driver: bridge
    name: sqler_postgres_net